name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Test
        run: go test -v ./...

      - name: Run functional tests
        run: go run cmd/tests/main.go -trapDetector -stop 0x00336D -start 0x0400 -rom testdata/6502_functional_test.bin
        timeout-minutes: 2
